[colors.primary]
foreground = "#{{white_hex}}"
background = "#{{black_hex}}"

[colors]
cursor = "#{{white_hex}}"

[colors.normal]
black = "#{{black_hex}}"
red = "#{{red_hex}}"
green = "#{{green_hex}}"
yellow = "#{{yellow_hex}}"
blue = "#{{blue_hex}}"
magenta = "#{{magenta_hex}}"
cyan = "#{{cyan_hex}}"
white = "#{{white_hex}}"

[colors.bright]
black = "#{{black_bright_hex}}"
red = "#{{red_bright_hex}}"
green = "#{{green_bright_hex}}"
yellow = "#{{yellow_bright_hex}}"
blue = "#{{blue_bright_hex}}"
magenta = "#{{magenta_bright_hex}}"
cyan = "#{{cyan_bright_hex}}"
white = "#{{white_bright_hex}}"
