# Shell variables
# Generated by 'walltheme'

# Special
background='#{{black_hex}}'
foreground='#{{white_hex}}'
cursor='#{{white_hex}}'

# Colors
color0='#{{black_hex}}'
color1='#{{red_hex}}'
color2='#{{green_hex}}'
color3='#{{yellow_hex}}'
color4='#{{blue_hex}}'
color5='#{{magenta_hex}}'
color6='#{{cyan_hex}}'
color7='#{{white_hex}}'
color8='#{{black_bright_hex}}'
color9='#{{red_bright_hex}}'
color10='#{{green_bright_hex}}'
color11='#{{yellow_bright_hex}}'
color12='#{{blue_bright_hex}}'
color13='#{{magenta_bright_hex}}'
color14='#{{cyan_bright_hex}}'
color15='#{{white_bright_hex}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
